### ISSUE TITLE
How to use with queue

### ISSUE THREAD

**Issue by galliroberto** [funkymed/tenant-aware-bundle#3]
I have a question about multi tenant and queue.
I set app a symfony multi app.
One app is multi-tenant.
I have separated cache and log for each tenant

If I run `php bin/console messenger:consume async` it takes the default connection.
Maybe in a message I have to store the tenantId and switch manually the connection or do you know a better solution?

I don't want to run a worker for tenant.

**Comment by funkymed** [comment]
Hello @galliroberto 
The best way to do so, is adding a processor to have differents parameters for your rabbitmq depending of your tenant

add a processor in this file `config/packages/tenant_aware.yaml`

```yaml
tenant_aware:
    processors:
        - Funkymed\TenantAwareBundle\DependencyInjection\Compiler\Processor\DummyProcessor
        - Funkymed\TenantAwareBundle\DependencyInjection\Compiler\Processor\DatabaseProcessor
        - ...
        - App\DependencyInjection\Compiler\Processor\YourRabbitMQProcessor
```

```php
<?php

// src/DependencyInjection/Compiler/Processor/YourRabbitMQProcessor.php

namespace App\DependencyInjection\Compiler\Processor;

use namespace Funkymed\TenantAwareBundle\DependencyInjection\Compiler\Processor\ProcessorAbstract;

// use this as an exemple to create your own replacement configuration
class YourRabbitMQProcessor extends ProcessorAbstract
{
    public function process()
    {
        // update your RabbitMQ configuration
    }
}
```

you will be able to do this after `php bin/console messenger:consume async --tenant=yourtenant`

Regards,
